# Generated by Django 4.1 on 2022-12-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping_source', '0002_rename_ai_mapping_result_getpartmappingsourceocrmodel_ai_ocr_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMappingResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
