# Generated by Django 4.1 on 2022-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetWinRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxNId', models.TextField(blank=True, null=True)),
                ('RFQFormID', models.TextField(blank=True, null=True)),
                ('LineItemRecordID', models.TextField(blank=True, null=True)),
                ('amount', models.TextField(blank=True, null=True)),
                ('rawMaterialCost', models.TextField(blank=True, null=True)),
                ('laborTime', models.TextField(blank=True, null=True)),
                ('laborCost', models.TextField(blank=True, null=True)),
                ('directMFGCosts', models.TextField(blank=True, null=True)),
                ('toolingCost', models.TextField(blank=True, null=True)),
                ('packingMatCost', models.TextField(blank=True, null=True)),
                ('totalMatYieldLoss', models.TextField(blank=True, null=True)),
                ('SMTFee', models.TextField(blank=True, null=True)),
                ('winRate', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
